@app.route("/movie", methods=["POST"])
#Decorator to make sure the jwt is included in the request
@jwt_required()
def movie_create():
    #Create a new movie
    movie_fields = movie_schema.load(request.json)

    new_movie = Movie()
    new_movie.title = movie_fields["title"]
    new_movie.genre = movie_fields["genre"]
    new_movie.length = movie_fields["length"]
    new_movie.year = movie_fields["year"]
    # not taken from the request, generated by the server
    new_movie.date = date.today()
    # add to the database and commit
    db.session.add(new_movie)
    db.session.commit()
    #return the card in the response
    return jsonify(movie_schema.dump(new_movie))


# def seed_db():

#     movie1 = Movie(
#         title = "Spider-Man: No Way Home",
#         genre = "Action",
#         length = 148,
#         year = 2021
#     )
#     db.session.add(movie1)

# @app.route("/auth/signin", methods=["POST"])
# def auth_signin():